# Generated by Django 5.1.1 on 2024-11-20 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='photos/branch')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('branch_location', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turul',
            fields=[
                ('turul_id', models.AutoField(primary_key=True, serialize=False)),
                ('turul_name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='photos/turul')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Baraa',
            fields=[
                ('baraa_id', models.AutoField(primary_key=True, serialize=False)),
                ('baraa_name', models.CharField(max_length=100)),
                ('baraa_une', models.IntegerField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('mashin_mark', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='photos/baraa')),
                ('description', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('turul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_app.turul')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('passwd', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_app.userrole')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='photos/worker')),
                ('geriinhayg', models.TextField(blank=True, null=True)),
                ('utasdugaar', models.CharField(blank=True, max_length=15, null=True)),
                ('position', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_app.branch')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('supply_id', models.AutoField(primary_key=True, serialize=False)),
                ('supply_date', models.DateTimeField(auto_now_add=True)),
                ('supplied_quantity', models.IntegerField()),
                ('baraa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_app.baraa')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_app.branch')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_app.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('baraa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_app.baraa')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_app.branch')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_app.worker')),
            ],
        ),
        migrations.CreateModel(
            name='BranchBaraa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_id', models.IntegerField()),
                ('item_count', models.IntegerField(default=0)),
                ('baraa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_app.baraa')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_app.branch')),
            ],
            options={
                'unique_together': {('sector_id', 'baraa')},
            },
        ),
    ]
