# Generated by Django 5.1.1 on 2024-12-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='user',
        ),
    ]
