# Generated by Django 5.1.1 on 2024-12-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0002_remove_worker_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='age',
        ),
        migrations.AddField(
            model_name='worker',
            name='born',
            field=models.DateField(blank=True, null=True),
        ),
    ]
