# Generated by Django 5.1.1 on 2024-12-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0003_remove_worker_age_worker_born'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='born',
        ),
        migrations.AddField(
            model_name='worker',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
